name: Generate SBOM
modu:
  push:
    branches: [ master ]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Changed to 18 for compatibility
      - name: Install dependencies
        run: npm ci
      - name: Install CycloneDX
        run: npm install -g @cyclonedx/cdxgen@10.10.0
      - name: Generate SBOM
        run: cdxgen -t javascript -o bom.json
      - name: Debug - Check file existence
        run: ls -la bom.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: bom.json
